### ISSUE TITLE
请注意 License

### ISSUE THREAD

**Issue by Justineo** [cenkai88/vue-svg-icon#1]
很明显这个项目基于 [vue-awesome](https://github.com/Justineo/vue-awesome) 扩展了一些功能，挺好的。但是 README、LICENSE 里都完全不提，LICENSE 里仅改成自己的名字，这似乎不妥吧。MIT 协议要求你在派生项目中带上原协议全文。

**Comment by cenkai88** [comment]
抱歉，晚上下班加上
