### ISSUE TITLE
图标没有加载出来，报了个错误

### ISSUE THREAD

**Issue by wh-Coder** [cenkai88/vue-svg-icon#13]
[Vue warn]: Error in render function: "ReferenceError: Symbol is not defined"

found in

<Icon>  ...\node_modules\vue-svg-icon\Icon.vue

**Comment by cenkai88** [comment]
你注意一下babel转码的时候，我代码里没有用Symbol这个全局变量，报这个应该是你babel转码的时候转出的版本用到了symbol这个es6里的全局变量但是浏览器没支持。

**Comment by wh-Coder** [comment]
@cenkai88 哦哦，图标在PC的chrome上一切正常，用安卓App的webview打开就会报这个错，不知道怎么搞了

**Comment by cenkai88** [comment]
@wh-Coder  嗯，我其他项目也遇到过这个问题，但是我那个项目简单，就手动吧symbol换成了for循环。你可以注意下转码的部分，根源都是Android浏览器不支持symbol
