### ISSUE TITLE
在电脑下icon正常显示,手机中浏览时icon消失

### ISSUE THREAD

**Issue by Fmain** [cenkai88/vue-svg-icon#19]
请问有没有遇到，在电脑下icon正常显示,手机中浏览时icon消失的情况。dev和打包后都是这样，不知道大家有没有遇到，或者只是我的代码其他问题

**Comment by cenkai88** [comment]
有可能是你的手机浏览器不支持svg元素
你的浏览器是啥

**Comment by Fmain** [comment]
哦哦,果然是浏览器的问题(〃'▽'〃) . 
还有个问题就是, 想把控制台的 console 去除掉, 看了下源码, 没找到加载svg时的console , 请问这个怎么去除
