### ISSUE TITLE
从iconfont 下载的svg有些图片为什么不能设置style调整颜色

### ISSUE THREAD

**Issue by leebo** [cenkai88/vue-svg-icon#2]
http://www.iconfont.cn/plus/collections/detail?cid=33
有很多都无法通过style 设置颜色 我已经设置成#000000 黑色了

**Comment by cenkai88** [comment]
你可以注意一下svg图标的源代码，必须全都是path标签。对应的illustrator里的概念就是复合路径，在illustrator里把原来那些rect（矩形），line（线段）等等对象按右键-建立复合路径再保存就可以了。以后可能会支持path以外的其他标签，最近有点忙没来得及改。
