### ISSUE TITLE
npm 安装npm install --save !xml-loader!../../src/svg  失败 求教

### ISSUE THREAD

**Issue by sunflower-tc** [cenkai88/vue-svg-icon#24]
安装loader的时候遇到了点问题
![image](https://user-images.githubusercontent.com/15952571/33208954-b84c43cc-d14e-11e7-928a-dcc30c2ae985.png)
请指点迷津谢谢

**Comment by Jeanallin** [comment]
Same issue

**Comment by sunflower-tc** [comment]
@Jeanallin  hello，you can npm install xml-loader --save-dev

**Comment by ZongDuCha** [comment]
安装了依然显示* !xml-loader!../../src/svg in ./node_modules/_babel-loader@7.1.2@babel-loader/lib!./node

**Comment by zepang** [comment]
@ZongDuCha 
you need to add loader to webpack config:
~~~js
module : {
  loaders : [
    { test: /\.xml$/, loader: 'xml-loader' } // will load all .xml files with xml-loader by default 
  ]
}
~~~

**Comment by ZongDuCha** [comment]
@zepang OK
