### ISSUE TITLE
没有 path 节点的 svg 不应该报错吧

### ISSUE THREAD

**Issue by bimohxh** [cenkai88/vue-svg-icon#3]
是这样的，很多 svg （http://ionicons.com/ 这上面有很多）是没有 path 这个节点的，但是用 vue-svg-icon 是会报错的，不知道能不能解决这个问题

**Comment by cenkai88** [comment]
目前是先要转换一下。这几天没空弄，这周末搞个自动转换的功能吧，到时候更新。感谢支持

**Comment by bimohxh** [comment]
^_^ 用着还不错

**Comment by cenkai88** [comment]
@bimohxh 搞定了，此外可以不用inject了。

**Comment by bimohxh** [comment]
谢谢！
