### ISSUE TITLE
Sketch Support

### ISSUE THREAD

**Issue by ghosh** [cenkai88/vue-svg-icon#5]
Hey,

Thanks for this package. It works great with illustrator.

Is it possible to make it work with Sketch?

**Comment by cenkai88** [comment]
Hi, I just tried sketch and I found the only difference is when you set the background color(the color that can be changed through CSS), set it as transparent instead of #000000 and don't cut the transparent pixels when you save the svg file.

**Comment by ghosh** [comment]
Ok got it. Thanks!
