### ISSUE TITLE
webpack2 里面报错

### ISSUE THREAD

**Issue by heshan-song** [cenkai88/vue-svg-icon#7]
[Vue warn]: Error in render function: 
(found in <Icon> at D:\vueTest\node_modules\.1.2.1@vue-svg-icon\Icon.vue)warn @ (program):568
(program):1453 TypeError: ["rect","circle","ellipse","polygon","line","path"].includes is not a function(…)handleError @ (program):1453

**Comment by cenkai88** [comment]
@heshan-song 应该是node版本的问题。。低版本不支持includes方法，我换个写法，稍等
