### ISSUE TITLE
放大的时候如何围绕中心放大

### ISSUE THREAD

**Issue by hatunet** [cenkai88/vue-svg-icon#8]
放大的时候如何围绕中心放大？
现在好像是围绕父元素左上端点开始放大。

**Comment by cenkai88** [comment]
是大小固定的么？大小固定可以用transform属性translateX, translateY调到50%就是中心放大了

**Comment by cenkai88** [comment]
@hatunet 可以用transform属性translateX, translateY调到50%，也可以用transform-origin属性
