### ISSUE TITLE
这个npm install --save !xml-loader!../../src/svg 下不下来啊

### ISSUE THREAD

**Issue by wh-Coder** [cenkai88/vue-svg-icon#9]

**Comment by cenkai88** [comment]
npm install --save xml-loader 吧

**Comment by yijie8** [comment]
我也是这样，，，在src/svg 把svg图标放进去，再启动vue就不出错了。

**Comment by ititchuan** [comment]
我已经有了src/svg目录了，图标也放进去了，还是不行啊

**Comment by ititchuan** [comment]
修改下源码的路径就可以了 找到 let xml = require(`!xml-loader!../../src/svg/${this.name}.svg`); 改为 let xml = require(`!xml-loader!/src/svg/${this.name}.svg`);
